CREATE DATABASE IF NOT EXISTS influmatch CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE influmatch;

CREATE TABLE types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE marques (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(255) NOT NULL,
  adresse VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE propositions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  montant DECIMAL(10,2) NOT NULL,
  description VARCHAR(255) NOT NULL,
  marque_id INT NOT NULL,
  type_id INT NOT NULL,
  image_pitch VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_propositions_marques FOREIGN KEY (marque_id) REFERENCES marques(id) ON DELETE CASCADE,
  CONSTRAINT fk_propositions_types FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
